USE TRABALHO;

-- 4.1
SELECT
  PROFESSOR.NOME_PROFESSOR AS PROFESSOR, 
  PROFESSOR.TITULACAO, 
  DISCIPLINA.NOM_DISCIPLINA AS DISCIPLINA, 
  DATE_FORMAT(TURMA.DTA_INICIO_AULAS, '%d/%m/%Y') AS 'INÍCIO AULAS', 
  DATE_FORMAT(TURMA.DTA_FIM_AULAS, '%d/%m/%Y') AS 'FIM AULAS', 
  COUNT(MATRICULA.RA) AS 'QTDE ALUNOS', 
  DISCIPLINA_OFERECIDA.BLOCO,
  DISCIPLINA_OFERECIDA.SALA,
  CASE 
    WHEN DISCIPLINA_OFERECIDA.DIA_SEMANA = 1 THEN 'Domingo' 
    WHEN DISCIPLINA_OFERECIDA.DIA_SEMANA = 2 THEN 'Segunda-feira' 
    WHEN DISCIPLINA_OFERECIDA.DIA_SEMANA = 3 THEN 'Terça-feira' 
    WHEN DISCIPLINA_OFERECIDA.DIA_SEMANA = 4 THEN 'Quarta-feira' 
    WHEN DISCIPLINA_OFERECIDA.DIA_SEMANA = 5 THEN 'Quinta-feira' 
    WHEN DISCIPLINA_OFERECIDA.DIA_SEMANA = 6 THEN 'Sexta-feira' 
    WHEN DISCIPLINA_OFERECIDA.DIA_SEMANA = 7 THEN 'Sábado' 
  END AS 'DIA SEMANA', 
  TIME_FORMAT(DISCIPLINA_OFERECIDA.HOR_INICIO, '%H:%i') AS 'HORÁRIO INICIO', 
  TIME_FORMAT(DISCIPLINA_OFERECIDA.HOR_FIM, '%H:%i') AS 'HORÁRIO FIM'
FROM 
  PROFESSOR 
  JOIN DISCIPLINA_OFERECIDA ON PROFESSOR.MATRICULA = DISCIPLINA_OFERECIDA.MATRICULA 
  JOIN TURMA ON DISCIPLINA_OFERECIDA.NUM_TURMA = TURMA.NUM_TURMA 
  JOIN MATRICULA ON TURMA.NUM_TURMA = MATRICULA.NUM_TURMA 
  JOIN ALUNO ON MATRICULA.RA = ALUNO.RA 
  JOIN DISCIPLINA ON DISCIPLINA_OFERECIDA.COD_DISCIPLINA = DISCIPLINA.COD_DISCIPLINA 
GROUP BY 
  PROFESSOR.NOME_PROFESSOR, 
  PROFESSOR.TITULACAO, 
  DISCIPLINA.NOM_DISCIPLINA, 
  TURMA.DTA_INICIO_AULAS, 
  TURMA.DTA_FIM_AULAS, 
  DISCIPLINA_OFERECIDA.SALA, 
  DISCIPLINA_OFERECIDA.BLOCO, 
  DISCIPLINA_OFERECIDA.DIA_SEMANA, 
  DISCIPLINA_OFERECIDA.HOR_INICIO, 
  DISCIPLINA_OFERECIDA.HOR_FIM;
  
  -- 4.2
  SELECT DISCIPLINA.NOM_DISCIPLINA AS 'DISCIPLINA', PROFESSOR.NOME_PROFESSOR AS 'PROFESSOR', 
       DISCIPLINA_OFERECIDA.BLOCO AS 'BLOCO', DISCIPLINA_OFERECIDA.SALA AS 'SALA', 
       CASE DISCIPLINA_OFERECIDA.DIA_SEMANA 
            WHEN 1 THEN 'Domingo' 
            WHEN 2 THEN 'Segunda' 
            WHEN 3 THEN 'Terça' 
            WHEN 4 THEN 'Quarta' 
            WHEN 5 THEN 'Quinta' 
            WHEN 6 THEN 'Sexta' 
            WHEN 7 THEN 'Sábado' 
       END AS 'Dia da Semana', 
       TIME_FORMAT(DISCIPLINA_OFERECIDA.HOR_INICIO, '%H:%i') AS 'HORÁRIO INICIO', 
       TIME_FORMAT(DISCIPLINA_OFERECIDA.HOR_FIM, '%H:%i') AS 'HORÁRIO FIM', 
       ALUNO.RA, ALUNO.NOME_ALUNO
FROM TURMA
INNER JOIN MATRICULA ON TURMA.NUM_TURMA = MATRICULA.NUM_TURMA AND MATRICULA.DTA_CANCELAMENTO_MATRICULA IS NULL
INNER JOIN DISCIPLINA_OFERECIDA ON MATRICULA.NUM_TURMA = DISCIPLINA_OFERECIDA.NUM_TURMA
INNER JOIN DISCIPLINA ON DISCIPLINA_OFERECIDA.COD_DISCIPLINA = DISCIPLINA.COD_DISCIPLINA
INNER JOIN PROFESSOR ON DISCIPLINA_OFERECIDA.MATRICULA = PROFESSOR.MATRICULA
INNER JOIN ALUNO ON MATRICULA.RA = ALUNO.RA
WHERE TURMA.DTA_INICIO_AULAS <= NOW() AND TURMA.DTA_FIM_AULAS >= NOW()
ORDER BY DISCIPLINA.NOM_DISCIPLINA, PROFESSOR.NOME_PROFESSOR, DISCIPLINA_OFERECIDA.BLOCO, DISCIPLINA_OFERECIDA.SALA, DISCIPLINA_OFERECIDA.DIA_SEMANA, DISCIPLINA_OFERECIDA.HOR_INICIO, ALUNO.NOME_ALUNO;


-- 4.3 

SELECT
DISCIPLINA.NOM_DISCIPLINA AS 'DISCIPLINA',
PROFESSOR.NOME_PROFESSOR AS 'PROFESSOR',
DISCIPLINA_OFERECIDA.BLOCO,
DISCIPLINA_OFERECIDA.SALA,

CASE
WHEN DISCIPLINA_OFERECIDA.DIA_SEMANA = 1 THEN 'Domingo'
WHEN DISCIPLINA_OFERECIDA.DIA_SEMANA = 2 THEN 'Segunda-feira'
WHEN DISCIPLINA_OFERECIDA.DIA_SEMANA = 3 THEN 'Terça-feira'
WHEN DISCIPLINA_OFERECIDA.DIA_SEMANA = 4 THEN 'Quarta-feira'
WHEN DISCIPLINA_OFERECIDA.DIA_SEMANA = 5 THEN 'Quinta-feira'
WHEN DISCIPLINA_OFERECIDA.DIA_SEMANA = 6 THEN 'Sexta-feira'
WHEN DISCIPLINA_OFERECIDA.DIA_SEMANA = 7 THEN 'Sábado'
END AS 'DIA SEMANA',

DISCIPLINA_OFERECIDA.HOR_INICIO AS 'HORÁRIO INICIO',
DISCIPLINA_OFERECIDA.HOR_FIM AS 'HORÁRIO FIM',
ALUNO.RA,
ALUNO.NOME_ALUNO AS NOME,
AVALIACAO.NOTA_A2 AS 'NOTA A2',
AVALIACAO.NOTA_A1 AS 'NOTA A1',
AVALIACAO.NOTA_AF AS 'NOTA AF',
CASE
WHEN (AVALIACAO.NOTA_A2 IS NULL) THEN 'REPROVADO'
WHEN (AVALIACAO.NOTA_A1 + AVALIACAO.NOTA_A2) >= 6 AND AVALIACAO.NOTA_AF IS NULL THEN 'APROVADO'
WHEN (AVALIACAO.NOTA_A1 + AVALIACAO.NOTA_AF) >= 6 THEN 'APROVADO'
WHEN (AVALIACAO.NOTA_A2 + AVALIACAO.NOTA_AF) < 6 THEN 'REPROVADO'
WHEN (AVALIACAO.NOTA_A1 + AVALIACAO.NOTA_A2) < 6 THEN 'AVALIAÇÃO FINAL'
ELSE 'Pendente'
END AS 'SITUAÇÃO ALUNO'
FROM
TURMA
JOIN MATRICULA ON TURMA.NUM_TURMA = MATRICULA.NUM_TURMA
JOIN ALUNO ON MATRICULA.RA = ALUNO.RA
JOIN DISCIPLINA_OFERECIDA ON MATRICULA.NUM_TURMA = DISCIPLINA_OFERECIDA.NUM_TURMA
JOIN DISCIPLINA ON DISCIPLINA_OFERECIDA.COD_DISCIPLINA = DISCIPLINA.COD_DISCIPLINA
JOIN PROFESSOR ON DISCIPLINA_OFERECIDA.MATRICULA = PROFESSOR.MATRICULA
LEFT JOIN AVALIACAO ON ALUNO.RA = AVALIACAO.RA AND DISCIPLINA_OFERECIDA.NUM_DISCIPLINA_OFERECIDA = AVALIACAO.NUM_DISCIPLINA_OFERECIDA
WHERE
TURMA.NUM_TURMA
ORDER BY
DISCIPLINA.NOM_DISCIPLINA,
ALUNO.NOME_ALUNO;

-- 4.4
