-- 1 
CREATE DATABASE TRABALHO
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_general_ci;

-- 2
USE TRABALHO;

CREATE TABLE Aluno(
RA INT NOT NULL AUTO_INCREMENT,
NOME_ALUNO VARCHAR(250) NOT NULL,
SEXO_ALUNO VARCHAR(1) NOT NULL, -- {Documentation F- Feminino/ M - Masculino}
CONSTRAINT PK_ALUNO PRIMARY KEY (RA))ENGINE = InnoDB;

CREATE TABLE PROFESSOR(
MATRICULA INT NOT NULL AUTO_INCREMENT,
NOME_PROFESSOR VARCHAR(250) NOT NULL,
TITULACAO VARCHAR(100) NOT NULL,
SEXO_PROFESSOR VARCHAR(1) NOT NULL, -- {Documentation F- Feminino/ M - Masculino}
CONSTRAINT PK_PROFESSOR PRIMARY KEY (MATRICULA))ENGINE = InnoDB;

CREATE TABLE TURMA(
NUM_TURMA INT NOT NULL AUTO_INCREMENT,
DTA_INICIO_AULAS DATE NOT NULL,
DTA_FIM_AULAS DATE NOT NULL,

CONSTRAINT PK_TURMA PRIMARY KEY (NUM_TURMA))ENGINE = InnoDB;

CREATE TABLE MATRICULA(
NUM_MATRICULA INT NOT NULL AUTO_INCREMENT, 
DTA_MATRICULA DATE NOT NULL,
DTA_CANCELAMENTO_MATRICULA DATE NULL,
RA INT NOT NULL,
NUM_TURMA INT,

CONSTRAINT PK_MATRICULA PRIMARY KEY (NUM_MATRICULA), 
CONSTRAINT FOREIGN KEY (RA) REFERENCES ALUNO(RA),
CONSTRAINT FOREIGN KEY (NUM_TURMA) REFERENCES TURMA(NUM_TURMA))ENGINE = InnoDB;

CREATE TABLE DISCIPLINA(
COD_DISCIPLINA INT NOT NULL AUTO_INCREMENT,
NOM_DISCIPLINA VARCHAR(250) NOT NULL,
CARGA_HORARIA INT NOT NULL,
CONSTRAINT PK_DISCIPLINA PRIMARY KEY (COD_DISCIPLINA))ENGINE = InnoDB;

CREATE TABLE DISCIPLINA_OFERECIDA(
NUM_DISCIPLINA_OFERECIDA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SALA VARCHAR(10) NOT NULL,
BLOCO VARCHAR(10) NOT NULL,
DIA_SEMANA INT NOT NULL, -- {Documentation = DEVE SER ENTRE 1- DOMINGO E 7 SABADO}
HOR_INICIO TIME NOT NULL,
HOR_FIM TIME NOT NULL,
COD_DISCIPLINA INT,
MATRICULA INT,
NUM_TURMA INT,

CONSTRAINT FOREIGN KEY (COD_DISCIPLINA) REFERENCES DISCIPLINA(COD_DISCIPLINA),
CONSTRAINT FOREIGN KEY (MATRICULA) REFERENCES PROFESSOR(MATRICULA), 
CONSTRAINT FOREIGN KEY (NUM_TURMA) REFERENCES TURMA(NUM_TURMA))ENGINE = InnoDB;


CREATE TABLE AVALIACAO(
SEQ_AVALIACAO_ALUNO INT NOT NULL AUTO_INCREMENT,
NOTA_A2 DECIMAL(5,2) NULL, -- {Documentation = DEVE ESTAR ENTRE 0 E 5}
NOTA_A1 DECIMAL(5,2) NULL, -- {Documentation = DEVE ESTAR ENTRE 0 E 5}
NOTA_AF DECIMAL(5,2) NULL, -- {Documentation = DEVE ESTAR ENTRE 0 E 5}
RA INT ,
NUM_DISCIPLINA_OFERECIDA INT,
CONSTRAINT PK_AVALIACAO PRIMARY KEY (SEQ_AVALIACAO_ALUNO), 
CONSTRAINT FOREIGN KEY (RA) REFERENCES ALUNO(RA),
CONSTRAINT FOREIGN KEY (NUM_DISCIPLINA_OFERECIDA) REFERENCES DISCIPLINA_OFERECIDA(NUM_DISCIPLINA_OFERECIDA))ENGINE = InnoDB;
